apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django
          image: lidymonteiro/k8s_dg:1.0.6
          command: ['/bin/sh', 'run.sh'] # runs migrations and starts the server
          ports:
            - containerPort: 8000
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: SQL_HOST
              value: postgres-service