version: '3.7'

services:
  web:
    container_name: django-container
    hostname: web-django
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: db-postgres
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - "5433"
    environment:
      - POSTGRES_USER=pybr2020
      - POSTGRES_PASSWORD=pyladies
      - POSTGRES_DB=bg_dev

volumes:
  postgres_data: